<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7f30f4d6b171: ccl_err + 0x8171 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb1)
	0x7f30f4d6e015: ccl_err + 0xb015 (_Z14err_terminatorv + 0x4b)
	0x7f30ecf03796: stdc++.so.6 + 0x63796 (_ZN10__cxxabiv111__terminateEPFvvE + 0x6)
	0x7f30ecf037c3: stdc++.so.6 + 0x637c3
	0x7f30ecf03a36: stdc++.so.6 + 0x63a36 (__cxa_rethrow + 0x46)
	0x7f31187bdb64: QtCore.so.4 + 0x1a5b64 (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x2f4)
	0x7f31187c27c4: QtCore.so.4 + 0x1aa7c4 (_ZN16QCoreApplication4execEv + 0xb4)
	   0x401ea8: quartus + 0x1ea8 (_Z8qgq_mainiPPKc + 0x68)
	0x7f30f75d9720: ccl_msg + 0x40720 (_Z15msg_main_threadPv + 0x10)
	0x7f30f492b02c: ccl_thr + 0x602c (thr_final_wrapper + 0xc)
	0x7f30f75d97df: ccl_msg + 0x407df (_Z18msg_thread_wrapperPFPvS_ES_ + 0x62)
	0x7f30f4f9e559: ccl_mem + 0xa559 (_Z18mem_thread_wrapperPFPvS_ES_ + 0x99)
	0x7f30f4d6bf92: ccl_err + 0x8f92 (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7f30f492b3f2: ccl_thr + 0x63f2 (thr_thread_wrapper + 0x15)
	0x7f30f75db7e2: ccl_msg + 0x427e2 (_Z12msg_exe_mainiPPKcPFiiS1_E + 0xa3)
	   0x401f7a: quartus + 0x1f7a (main + 0x26)
	0x7f30ec7600b3: c.so.6 + 0x270b3 (__libc_start_main + 0xf3)
	   0x401d59: quartus + 0x1d59
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Tue Nov 24 21:47:39 2020
</date>
<version>Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition</version>
</internal_error>